package com.example.impactx.data.local;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Tracks every Wear OS event (START_TRIP, IMPACT_DETECTED, SOS, FINISH_TRIP)
 * with idempotency via eventId UNIQUE constraint.
 * Status lifecycle: PENDING → SUCCEEDED | FAILED
 * FAILED events can be retried with the same eventId.
 */
@Entity(tableName = "wear_sync_events")
public class WearSyncEventEntity {

    @PrimaryKey(autoGenerate = true)
    public int rowId;

    /** UUID generated by the wearable — globally unique per event. */
    @ColumnInfo(index = true)
    public String eventId;

    /** START_TRIP | IMPACT_DETECTED | SOS | FINISH_TRIP */
    public String eventType;

    /** PENDING | SUCCEEDED | FAILED */
    public String status;

    public String createdAtUtc;
    public String updatedAtUtc;

    /** tripId or accidentId returned by the backend on success */
    public String backendEntityId;

    /** HTTP response code from the backend call */
    public int httpCode;

    /** Sanitized error message (never logs JWT/passwords) */
    public String errorMessage;
}
