package com.example.impactx.data.local;

import androidx.annotation.NonNull;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Tracks every Wear OS event (START_TRIP, IMPACT_DETECTED, SOS, FINISH_TRIP)
 * with idempotency via eventId PRIMARY KEY.
 * Status lifecycle: PENDING → SUCCEEDED | FAILED
 * FAILED events can be retried with the same eventId.
 */
@Entity(tableName = "wear_sync_events")
public class WearSyncEventEntity {

    /** UUID generated by the wearable — globally unique per event. */
    @PrimaryKey
    @NonNull
    public String eventId;

    /** nodeId of the Wear OS device that emitted this event. */
    public String sourceNodeId;

    /** START_TRIP | IMPACT_DETECTED | SOS | FINISH_TRIP */
    public String eventType;

    /** PENDING | SUCCEEDED | FAILED */
    public String status;

    /** tripId or accidentId returned by the backend on success */
    public String backendTripId;

    /** HTTP response code from the backend call (nullable) */
    public Integer httpCode;

    /** Sanitized error message (never logs JWT/passwords) */
    public String errorMessage;

    public String createdAt;
    public String updatedAt;

    public WearSyncEventEntity() {
        this.eventId = "";
    }
}
